name: "ZAP Baseline Scan"

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/zap_scan.yml'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/zap_scan.yml'
  # schedule:
  #   - cron:  '0 18 * * 6'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@7c4deb10e6261301961c86d65d54a516394f9aed # v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.juice-shop.shrine-gong.ai'
          rules_file_name: 'juice-shop/.zap/rules.tsv'
          cmd_options: '-a -j'