name: "ZAP Baseline Scan"

on:
  push:
    branches:
      - stage
    paths:
      - "juice-shop/**"
      - ".github/workflows/zap_scan.yml"
  pull_request:
    branches:
      - stage
    paths:
      - "juice-shop/**"
      - ".github/workflows/zap_scan.yml"
  # schedule:
  #   - cron:  '0 18 * * 6'

permissions:
  issues: write
  contents: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Caprover
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: ZAP Scan
        uses: zaproxy/action-baseline@7c4deb10e6261301961c86d65d54a516394f9aed # v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.juice-shop.shrine-gong.ai'
          rules_file_name: 'juice-shop/.zap/rules.tsv'
          cmd_options: '-a -j'
          allow_issue_writing: false
          artifact_name: 'zap-scan-report'